### ISSUE TITLE
FR12.  Create New Settings Group

### ISSUE THREAD

**Issue by n898c** [WSU-4110/AppSettingsManager#19]
|FR12: Create New Settings Group|
|---|
|**Goal**: Users can create new variable/settings groups within the App Settings Manager
**Stakeholders:** Project Managers|
| **Description:** Any user can create a new grouping of settings/variables in the App Settings Manager. That user will automatically become the project manager (will have approval-access) of that grouping.|
| **Origin:** Based on the initial project specification document, team members came up with this description during the second meeting.|
| **Version:** 1.0  |
|**Date:** 02/01/2023
|  **Priority:** 1 |

**Comment by flennaja** [comment]
This is somewhat implemented already. But when a new SettingGroup is created, the User who created it will need to automatically have Admin access. Otherwise no one will ever be able to edit the SettingGroup

**Comment by arushwolf** [comment]
Hey @MsMarini, I am looking into this as I was the one that did the CRUD operations for Settings groups, sorry for the late heads-up. Unless you have already figured it out, if so, I apologize, I will let you go along with your progress.
