### ISSUE TITLE
FR14.  Login

### ISSUE THREAD

**Issue by n898c** [WSU-4110/AppSettingsManager#21]
|FR14.  Login|
|---|
|**Goal**: Users that have an account stored in the App Settings Manager will be able to log in to their account
**Stakeholders:** All|
| **Description:** Users can log into their accounts through the App Settings Manager webpage by providing their username and password. Any settings/variable groupings that they have access to will be displayed to them.|
| **Origin:** Based on the initial project specification document, team members came up with this description during the second meeting.|
| **Version:** 1.0  |
|**Date:** 02/01/2023
|  **Priority:** 1 |

**Comment by flennaja** [comment]
For the most part this will be handled in Angular actually. There are packages already that manage states in the UI between being logged out and logged in. However, our methods will always need to check UserId/Password for access to whatever method on each request
