### ISSUE TITLE
FR15.  Input Format Checking

### ISSUE THREAD

**Issue by n898c** [WSU-4110/AppSettingsManager#22]
|FR15: Input Format Checking|
|---|
|**Goal**: Changes that are submitted to the App Settings Manager will have their format verified
**Stakeholders:** All|
| **Description:** When setting/variable changes are submitted to the App Settings Manager, the changes are validated against requirements previously specified. For instance, if a variable is supposed to be an integer, then the App Settings Manager should display an error message if someone tries changing that variable to “Hello World!”|
| **Origin:** Based on the initial project specification document, team members came up with this description during the second meeting.|
| **Version:** 1.0  |
|**Date:** 02/01/2023
|  **Priority:** 2 |

**Comment by flennaja** [comment]
Deferred to sprint 3
